module.exports = {
  "auther": "Dan Beaven",
  "posts": [
    {
      "title": "Measuring the impact culture has on the economy",
      "date": 1446940800000,
      "sections": [
        {
          "title": "Introduction",
          "paragraphs": [
            { "text": "Economic value in the Cambridge English dictionary is defined as ‘the value of an asset calculated according to its ability to produce income in the future’ (Cambridge Dictionary 2016). This definition when applied to culture and the arts may not fit so well since much of the value we find in culture is not monetary. Neoclassical economics has a broader definition, it defines value as the rational preference of one outcome over another (Weintraub, 1993). This definition allows us to look more broadly at value while staying within the economic confines of rational thought. In this essay, I start by defining what I am referring to when I use the term the culture. Using the neoclassical definition of value, I try and pick apart what cultural commodities are and how they are different to other goods and services. I look at ways of measuring this value and the problems that arise as a result. Finally, I look at why measuring the value of culture matters at all." },
          ]
        },
        {
          "title": "What is culture",
          "paragraphs": [
            { "text": "The word culture is hard to define and hotly contested though most people do having an intuitive sense of its meaning. Raymond Williams who has written much on the subject of culture defines first the independent noun ‘culture’, as indicating ‘particular way of life, whether of a people, a period, a group, or humanity in general’. Williams defines the abstract noun ‘culture’ as describing ‘the works and practices of intellectual and especially artistic activity’ (Williams, 1983, p.87). These definitions allow us to talk about culture in reference to a way of life and talk about art as a cultural commodity." },
          ]
        },
        {
          "title": "How to measure economic value of culture",
          "paragraphs": [
            { "text": "There are three main methods economists use to measure the value of industries, sectors or goods, these include economic impact assessment, measuring size or footprint, cultural satellite accounts. Impact assessment can be split into three subcategories, direct impacts, indirect impacts and induced impacts. Direct impacts are the gross value of the goods and services (GVA) and the cost of employment. Indirect impacts are the economic impacts through the supply chain. Induced impacts are the effects of the spending by those employed within the industries. Size or footprint analysis is used to understand whether a sector is significant to the economy however, it doesn’t include indirect effects and so the information it gives is limited. Cultural satellite accounts look at many cultural industries accounts in including the accounts of the suppliers and distributors in order to evaluate the national contribution. This is often used when measuring the size of sectors that are not industries such as tourism or unpaid housework. (Crossick and Kaszynska, 2016, p89-90)" },
            { "text": "The most popular of the three methods for calculating the value of cultural commodities are economic impact studies, ‘the one that resonates most with elected leaders, public and private sector funders, and policymakers—is the economic impact study’ (Sterngold, 2004, p167), however there is a body of work criticizing this approach to measuring the value of cultural sectors. Sterngold notes that problems arise when substitution effects are not taken into account. For example, you might want to measure the potential economic impact of a new cinema, it is not enough to just measure the gross income generated because a proportion of that income will be income originally generated by another business. In other words by funding a project like a cinema you might just be shifting people's spending from one business to another and not actually generating new wealth for the regen (Sterngold, 2004). It is also important to note that impact studies are not an exact science but a best estimate if multiple impact studies are done they will in all probability yield different results (Crompton, Lee, and Shuster, 2001). Because of this, it is important to be critical of impact studies done and especially any vested interest of authors or funding bodies." },
            { "text": "Broader problems arise from using an economic approach to measuring the value of cultural commodities in general, since classical economics treats people as purely rational decision makers, in other words, it assumes individuals will take a logical approach to maximising economic profit. This does not seem to be the case with artistic labour where ‘financial rewards are generally lower’ and there is a  ‘high variability of artists earnings’ (Ginsburgh, 2006, p9). Ginsburgh also notes the there are  ‘non-pecuniary motives where artists care more about their work than financial incentives’ (Ginsburgh, 2006, p9)." },
            { "text": "It is important to also mention social return on investment (SROI) which is an alternative method used to calculate the social value of cultural projects, that in recent years has gained popularity. The method produces a ratio which is supposed to reflect the ratio of monetary investment value, to the social return value. A key aspect of the SROI method is that it stresses the importance of a ‘detailed report containing qualitative, quantitative and financial data that explains the judgements and decisions made over the course of the analysis’ (Jardine and Whyte, 2013, p22). A detailed qualitative and quantitative report might help to eliminate the problem that impact assessments suffer from which is that they are hard for non-economists to fully understand and so be critical of." },
          ]
        },
        {
          "title": "Why the measure economic value of cultural commodities",
          "paragraphs": [
            { "text": "All government funding decisions are subject to opportunity cost (Crossick, p90, 2016), meaning each decision to fund one cause is also the decision not to fund another. If policy makers and funding bodies can see not only public support but imperative evidence that funds in a cultural project will generate jobs and wealth for the country/regen it will make decisions between say in investment in a science project or cultural project much clearer. There are also the ‘voluntary/third sector and charities who are under increasing pressure to evidence their effectiveness’ (Jardine and Whyte, 2013, p1)." },
            { "text": "In a study completed in 2013 on the value of the British Library, Andrew Tessler uses benefit-cost analysis (BCA) to calculate a benefit-cost ratio (BCR). This is done by weighing up all the benefits and dividing by all the costs. To estimate the value of the the library Tessler uses Total Economic Valuation (TEV) which takes account of both use values and non-use values. The ‘use values’ are all the benefits felt by users of the library such as the reading-rooms, document supply, web-services etc. The ‘non-use values’ are ‘existence values’ which is ‘The value attached to the existence of the Library irrespective of whether a person ever visits it or not  (Oxford Economics, 2013, p46).’, ‘bequest value’,  ‘The value which the current generation places on preserving the Library for the benefit of future generations (Oxford Economics, 2013, p46)’ and ‘option value’, ‘This represents the value attached to potential future benefits from the Library’ (Oxford Economics, 2013, p46). To work out the values of the amenities offered by the library they surveyed users asking how much the users were willing to pay (WTP) for their usage. For ‘non-use values’ surveys were sent out to nation wide ‘as to ensure that the respondents reflected the UK population distribution (Oxford Economics, 2013, p47)’. 55% of the surveys received back were from people who had never heard of or used the library and by asking ‘If you were free to choose how your existing taxes were allocated, what would be the maximum you would be willing to pay’, the average amount received back was £8.15 which is over double what is currently being paid. The study concluded that ‘The benefit cost ratio of 4.9 indicates that for every £1 invested in the Library in 2011/12, the Library generated £4.90 in economic welfare (Oxford Economics, 2013, p52)’. (Oxford Economics, 2013)" },
            { "text": "The total economic evaluation of the british library highlights two important things first that people can value something without ever experiencing or using it and second that there can be significant both social and economic return on an investment which might not be immediately obvious." },
          ]
        },
        {
          "title": "Conclusion",
          "paragraphs": [
            { "text": "It seems clear that if possible the ability to define the true economic value of goods and services within the cultural sector could not only benefit the public but also those making the funding decisions. ‘Public policy and public funding are a crucial part of the overall landscape occupied by arts and culture’ (Crossick, p154, 2016). The real difficulties arise when knowing whether the numbers you have come up with truly reflect the actual value. In this essay, I have addressed the cultural sector as a whole rather than looking at its constituent parts. This might be the wrong way of addressing the question ‘how to measure economic value?’, it might be better to focus on sectors of culture such as the music, museums, public art, architecture etc. There are of course other ways to measure the value of culture, one of the most promising being (SROI), which might do a much better job of reflecting the true value culture has to people and society. It seems there is still too little evidence to say which method of quantifying value is the most accurate and it is likely that the best method will be specific to the situation it’s used in." },
          ]
        },
      ],
      "references": [
        { "text": "Cambridge Dictionary (2016) Economic value meaning in the Cambridge English dictionary. Available at: http://dictionary.cambridge.org/dictionary/english/economic-value?fallbackFrom=learner-english&q=Economic+value (Accessed: 5 December 2016)." },
        { "text": "Crompton, John L., Seokho Lee, and Thomas J. Shuster. 2001. A guide for undertaking economic impact studies: The Springfest example. Journal of Travel Research 40:79–87." },
        { "text": "Crossick, G. and Kaszynska, P. (2016) ‘Understanding the value of arts & culture’, The AHRC Cultural Value Project" },
        { "text": "E. Roy Weintraub, (1993). 'Neoclassical Economics.' The Concise Encyclopedia of Economics. Library of Economics and Liberty. Retrieved from http://www.econlib.org/library/Enc1/NeoclassicalEconomics.html" },
        { "text": "Geursen, G. and Rentschler, R. (2003) ‘Unraveling Cultural Value’, The Journal of Arts Management, Law, and Society, 33(3), 196-210. doi: 10.1080/10632920309597346" },
        { "text": "Ginsburgh, V. and Throsby, D. (2006) Handbook of the economics of art and culture. North Holland" },
        { "text": "Jardine, C. and Whyte, B. (2013), ‘Valuing Desistence? A Social Return on Investment Case Study of a Throughcare Project for Short-Term Prisoners’. Social and Environmental Accountability Journal, Vol. 33, No. 1, 20–32, http://dx.doi.org/10.1080/0969160X.2013.768088" },
        { "text": "Nelson, P. (1970). 'Information and Consumer Behavior’, Journal of Political Economy, Vol. 78, No. 2 (Mar. - Apr., 1970), pp. 311-329 http://www.jstor.org/stable/1830691" },
        { "text": "O’Brien, D. (2010). Measuring the Value of Culture: a report to the Department for Culture Media and Sport. London: DCMS. Retrieved from https://www.gov.uk/government/uploads/ system/uploads/attachment_data/file/77933/measuring-thevalue-culture-report.pdf" },
        { "text": "Oxford Economics. (2013). Economic Valuation of the British Library. Oxford: Oxford Economics. Retrieved from www.oxfordeconomics.com/my-oxford/projects/245662" },
        { "text": "Sterngold, A.H. (2004). Do economic impact studies misrepresent the benefits of arts and cultural organizations? Journal of Arts Management, Law, and Society, 34 (3), 166-187" },
        { "text": "Throsby, D. (2003). ‘Determining the Value of Cultural Goods: How Much (or How Little) Does Contingent Valuation Tell Us?’, Journal of Cultural Economics. doi:10.1023/A:1026353905772" },
        { "text": "Williams, R. (1983). ‘A vocabulary of culture and society’, Oxford University Press. Retrieved from https://tavaana.org/sites/default/files/raymond-williams-keywords.pdf" },
      ]
    },

    {
      "title": "What is culture",
      "date": 1477872000000,
      "sections": [
        {
          "title": "",
          "paragraphs": [
            { "text": "It is important especially in academic writing to have clear definitions for words and terms used. This is not always easy, meanings are continually changing and many words have more than one meaning depending on the context. In this post I try to investigate the true definition and where the word came from." },
            { "text": "The Oxford english dictionary defines culture as 'The arts and other manifestations of human intellectual achievement regarded collectively' (Oxford English Dictionary, 2016). The Cambridge english dictionary  defines culture as 'the way of life, especially the general customs and beliefs, of a particular group of people at a particular time' (Cambridge Dictionary, 2016)." },
            { "text": "The history of the word starts in medieval times and comes from the word cultivate when referring to the ‘cultivation of land’ (Williams, 2016, p. 242). The latin french origins cultura and culture respectively also refer to farming land. The first sign of its meaning changing was Thomas Hobbes's Leviathan first published 1651 which uses culture to describe the education of children, ‘the education of Children a Culture of their minds’ (Hobbes, 2008, p. 163). Raymond Williams (1953), describes William Wordsworth's use of the word in The Prelude (1995) as ‘genuinely transitional’; when he uses the word in both the older sense of process, ‘be left to droop by timely culture unsustained’, but also uses it as an absolute, ‘Salutes the Being at his birth, where grace of culture hath been utterly unknown’. This according to Raymond Williams was the first time culture was used in the modern sense of the word (Williams, 1953)." },
            { "text": "The search for a definition of culture felt like traversing a tangled web of ambiguity leading from one historical piece of literature to the next. There was no single definition which encapsulated all of the meanings but maybe that's okay, maybe the job of someone using the term is to clearly define the context they use it in." }
          ]
        }
      ],
      "references": [
        { "text": "Cambridge Dictionary (2016) Culture meaning in the Cambridge Learner’s dictionary. Available at: http://dictionary.cambridge.org/dictionary/learner-english/culture (Accessed: 5 December 2016)." },
        { "text": "Hobbes, T. (2008) Leviathan (Oxford world’s classics). Edited by J. C. A. Gaskin. Oxford: Oxford University Press, USA." },
        { "text": "Oxford English Dictionary (2016) Available at: https://en.oxforddictionaries.com/definition/culture (Accessed: 5 December 2016)." },
        { "text": "Williams, R. (1953) ‘The Idea of Culture’, The Cambridge Quarterly, 3(3)." },
        { "text": "Wordsworth, W. (1995) The prelude: The Four texts (1798, 1799, 1805, 1850): Four texts (1798, 1799, 1805, 1850). Edited by Jonathan Wordsworth. New York: Penguin Group (USA)." },
      ]
    }
  ]
}
